server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
# Car service
        - id: car-service
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars
            - Method=POST
          filters:
            - SetPath=/api/car

        - id: car-service-all
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars/all
            - Method=GET
          filters:
            - SetPath=/api/car/all

        - id: car-service-id
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars/{id}
            - Method=GET
          filters:
            - SetPath=/api/car/{id}
#Mechanic Service
        - id: mechanic-service
          uri: http://${MECHANIC_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/mechanics
            - Method=POST
          filters:
            - SetPath=/api/mechanics

        - id: mechanic-service-all
          uri: http://${MECHANIC_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/mechanics/all
            - Method=GET
          filters:
            - SetPath=/api/mechanic/all
#Garage Service
        - id: garage-service-repair
          uri: http://${GARAGE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/garages/repair
            - Method=POST
          filters:
            - SetPath=/api/garage/repair

        - id: garage-service-all
          uri: http://${GARAGE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/garages/all
            - Method=GET
          filters:
            - SetPath=/api/garage/all

        - id: garage-service-repaired
          uri: http://${GARAGE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/garages/repaired/{id}
            - Method=PUT
          filters:
            - SetPath=/api/garage/repaired/{id}

        - id: garage-service-bill
          uri: http://${GARAGE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/garages/bill/{id}
            - Method=GET
          filters:
            - SetPath=/api/garage/bill/{id}

        - id: garage-service-pay
          uri: http://${GARAGE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/garages/pay/{id}
            - Method=PUT
          filters:
            - SetPath=/api/garage/pay/{id}